# Generated by Django 4.1.7 on 2023-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='tammy@gmail.com')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
